name: go_provider
description: "Easily scope providers to routes with GoProviderRoute and ShellProviderRoute."
version: 1.8.2
homepage: https://www.bravier.com
repository: https://github.com/arthurbcd/go_provider.git
topics:
 - go-router
 - provider
 - scope
 - nested

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: '>=14.5.0 <17.0.0'
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
